name: vidhi_portfolio
description: Vidhi Mochi - Flutter Developer Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_bottom_navigation: ^2.4.0
  google_fonts: ^8.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/vm_portfolio_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/